<div class="tcb-flex flex-dir-column mt-10">
	<div class="tcb-flex space-between tcb-relative">
		<select id="c-s-p-palettes-select" class="change" data-fn="dom_change_palette"></select>
		<span class="c-s-p-palettes-arrow"><?php tcb_icon('a_down'); ?></span>
		<a href="javascript:void(0);" class="c-s-p-palettes-action-btn click" data-fn="dom_reset_active_palette" data-position="top" data-tooltip="<?php echo __( 'Reset Active Palette', 'thrive-cb' ); ?>"><?php tcb_icon('sync-regular'); ?></a>
	</div>
</div>
