<div class="api-field tve-zapier-api-wrapper">
	<div class="col-xs-12">
		<label class="tcb-checkbox">
			<input id="zapier_send_ip" class="tve-checkbox tve-api-extra" type="checkbox" <#= 1 == api.getConfig('send_ip') ? 'checked="checked"' : '' #> />
			<span>
				<?php echo __( 'Send IP Address', 'thrive-cb' ); ?>
			</span>
		</label>
	</div>

	<div class="tve-zapier-data">
		<div class="row">
			<div class="col-xs-12">
				<div class="tvd-input-field">
					<input id="zapier_tags" type="text" class="tve-api-extra" name="tags" value="<#= api.getConfig('tags') ? api.getConfig('tags') : '' #>"/>
					<label for="zapier_tags"><?php echo __( 'Tags', 'thrive-cb' ) ?></label>
				</div>
			</div>
		</div>

		<div class="field-description mt-10 mb-10">
			<?php echo __( 'Comma-separated lists of tags', 'thrive-cb' ) ?>
		</div>

		<input id="thriveleads_group" type="hidden" class="tve-api-extra" name="thriveleads_group" value="<#= api.getConfig('thriveleads_group_id') ? api.getConfig('thriveleads_group_id') : '' #>"/>
		<input id="thriveleads_type" type="hidden" class="tve-api-extra" name="thriveleads_type" value="<#= api.getConfig('thriveleads_type') ? api.getConfig('thriveleads_type') : '' #>"/>
		<input id="thriveleads_name" type="hidden" class="tve-api-extra" name="thriveleads_name" value="<#= api.getConfig('thriveleads_name') ? api.getConfig('thriveleads_name') : '' #>"/>
		<input id="source_url" type="hidden" class="tve-api-extra" name="source_url" value="<#= encodeURIComponent( window.location.href ) #>"/>
	</div>
</div>
